### ISSUE TITLE
Failure in Re-serialize logic due to the new property IsComponentDefinition

### ISSUE THREAD

**Issue by LinnZawWin** [daryllabar/CanvasAppPackager#12]
The unpack action fails with the following error when the CanvasAppPackager runs on the canvas app due to the new "IsComponentDefinition" property of the app.

`System.Exception: Unable to re-serialize json to match source!  Character at position: 318 on line: 11 at 8 is not correct.  To prevent potential app defects, extracting file C:\.....................\Extract\Apps\Power Flappy\Controls\1.json has stopped.`

The repro app can be downloaded [here](https://1drv.ms/u/s!Ai-uZ1F-rHmWgrJJvQi5Crq6rIl_RA?e=u9efcn) for troubleshooting

**Comment by daryllabar** [comment]
The problem is your app is not on the latest version of the JSON Docs.  You should edit the app in the Canvas Apps Studio so it upgrades to the latest version, and then re-export it.  Creating another issue to handle checking for the DocVersion in the Header.json
