### ISSUE TITLE
Remove Components Version and LastModifiedTimestamp Noisy Diffs

### ISSUE THREAD

**Issue by daryllabar** [daryllabar/CanvasAppPackager#24]
![image](https://user-images.githubusercontent.com/9728423/74164278-8e033d80-4bf1-11ea-9ad7-eaa2071770b4.png)

**Comment by MikeStall** [comment]
Is this something you plan to handle in the tool, or do you need a product change? Do you want to create a tag / label for issues that need a requested product change?

**Comment by daryllabar** [comment]
@MikeStall I was planning to handle this in my tool.  I'm already doing it for normal controls, but I haven't done it for components yet.  Although if you don't handle this in the product, you're tooling will have to handle it somehow.

**Comment by daryllabar** [comment]
Not going to fix.
