### ISSUE TITLE
hostfxr.dll missing

### ISSUE THREAD

**Issue by compunuke** [daryllabar/CanvasAppPackager#36]
When attempting to execute:
CanvasAppPackager /a:unpack /z:"..\T&S Feedback App_v01_01.msapp" /f:"..\T&S Feedback App_v01_01_unpack"
after downloading your v1.0.0.21

I am getting the following error:
A fatal error occurred. The required library hostfxr.dll could not be found.
when executing on Windows 10.0.18363

Should this dll be included in your zip?
I am not admin on my corporate machine so I need justification to have sysadmins help with unauthorized installs.
Can the dll be added without install as the dlls in your app folder are?

**Comment by daryllabar** [comment]
This is because you are missing the .net core run time in the machine, and the app is created as a framework dependent application.  If you're a dev, you should be able to just download the code and run it

**Comment by daryllabar** [comment]
I would also recommend checking out https://github.com/microsoft/PowerApps-Language-Tooling at some point in the future as well, since Microsoft now has their own version of the tool that they will be supporting.
